"""Canonical contract model namespace for Contexta."""

from .artifacts import ARTIFACT_KINDS, ArtifactManifest
from .context import (
    BatchExecution,
    DEFAULT_CONTRACT_SCHEMA_VERSION,
    DeploymentExecution,
    EnvironmentSnapshot,
    OperationContext,
    Project,
    RUN_STAGE_STATUSES,
    Run,
    SampleObservation,
    StageExecution,
)
from .records import (
    COMPLETENESS_MARKERS,
    DEGRADATION_MARKERS,
    DEGRADED_CATEGORIES,
    DEGRADED_SEVERITIES,
    EVENT_LEVELS,
    METRIC_AGGREGATION_SCOPES,
    ORIGIN_MARKERS,
    RECORD_TYPES,
    TRACE_SPAN_KINDS,
    TRACE_SPAN_STATUSES,
    CorrelationRefs,
    DegradedPayload,
    DegradedRecord,
    MetricPayload,
    MetricRecord,
    RecordEnvelope,
    StructuredEventPayload,
    StructuredEventRecord,
    TraceSpanPayload,
    TraceSpanRecord,
)
from .lineage import (
    ASSERTION_MODES,
    CONFIDENCE_MARKERS,
    LINEAGE_ORIGIN_MARKERS,
    RELATION_TYPES,
    LineageEdge,
    ProvenanceRecord,
)

__all__ = [
    "ARTIFACT_KINDS",
    "ASSERTION_MODES",
    "COMPLETENESS_MARKERS",
    "CONFIDENCE_MARKERS",
    "CorrelationRefs",
    "DEGRADATION_MARKERS",
    "DEGRADED_CATEGORIES",
    "DEGRADED_SEVERITIES",
    "DEFAULT_CONTRACT_SCHEMA_VERSION",
    "DeploymentExecution",
    "EnvironmentSnapshot",
    "EVENT_LEVELS",
    "ArtifactManifest",
    "BatchExecution",
    "DegradedPayload",
    "DegradedRecord",
    "LINEAGE_ORIGIN_MARKERS",
    "LineageEdge",
    "METRIC_AGGREGATION_SCOPES",
    "MetricPayload",
    "MetricRecord",
    "OperationContext",
    "ORIGIN_MARKERS",
    "Project",
    "ProvenanceRecord",
    "RECORD_TYPES",
    "RELATION_TYPES",
    "RecordEnvelope",
    "RUN_STAGE_STATUSES",
    "Run",
    "SampleObservation",
    "StageExecution",
    "StructuredEventPayload",
    "StructuredEventRecord",
    "TRACE_SPAN_KINDS",
    "TRACE_SPAN_STATUSES",
    "TraceSpanPayload",
    "TraceSpanRecord",
]
